### ISSUE TITLE
Bugs discovered

### ISSUE THREAD

**Issue by omegafishy** [CS2103-AY1819S1-W14-3/main#131]
1. During my systems testing, I discovered command bugs that apply for adddiet, addapt, adddiet and visitorin. By pasting copies of valid inputs into the command line,  I created the following test inputs that were deemed valid by the parser. This should not be the case. Try replicating the inputs on your applications.

@yuntongzhang 
- `adddiet ic/S1234567A alg/Egg alg/Crab cr/Halal pd/Hands cannot move. adddiet ic/S1234567A alg/Egg alg/Crab cr/Halal pd/Hands cannot move. `

@jeffypie369 
- `addappt ic/S1234567A type/SRG pn/Brain transplant dt/27-04-2019 10:30 doc/Dr. Pepperaddappt ic/S1234567A type/SRG pn/Brain transplant dt/27-04-2019 10:30 doc/Dr. Pepper`

@snajef 
- `addmeds ic/S1234567A d/Paracetamol q/2 u/tablets n/4 t/14addmeds ic/S1234567A d/Paracetamol q/2 u/tablets n/4 t/14`

@GAOJIAXIN666 
- `visitorin ic/S1234567A v/Janevisitorin ic/S1234567A v/Jane`

The following input fails, but throws an irrelevant exception message. I will resolve this.
 - `addmh ic/S9271847A mh/Patient has acute terminal stage brain cancer, refer to Dr.Zhang immediately. doc/Dr.Ross addmh ic/S9271847A mh/Patient has acute terminal stage brain cancer, refer to Dr.Zhang immediately. doc/Dr.Ross`

2. Another bug discovered for addappt and adddiet feature.
Whenever addappt and adddiet is carried out for a particular patient, all other data of the patient is lost.
This may be due to the implementation of the `addDietsForPatient` and the `addApptForPerson` method, as they do not include the other information fields such as MedicalHistory in the Person constructor.

Do take a look @yuntongzhang  @jeffypie369 .

**Comment by snajef** [comment]
Bug reproduced on latest release.

`addmeds ic/S1234567A d/Paracetamol q/2 u/tablets n/4 t/14addmeds ic/S1234567A d/Paracetamol q/2 u/tablets n/4 t/14` appears to have the same result as `addmeds ic/S1234567A d/Paracetamol q/2 u/tablets n/4 t/14`.

The prefix system used to parse input seems to return the last input for a given prefix if multiple inputs are given. This is expected behaviour documented in `ArgumentMultimap::getValue`. As such, this might not classify as a bug, but more so of unexpected behaviour.

As fixing this would require a significant overhaul of the `ArgumentMultimap` class, I suggest updating the user guide to note this behaviour, and cautioning users that such behaviour will occur when trying to use such unusual input.
